version: "3.7"
services:
  redis:
    image: redis
    volumes:
      - ./data:/data
    ports:
      - 6379:6379
    restart: always
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports: 
      - "6666:6666"
    depends_on: 
      - redis
    restart: always
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports: 
      - 3000:3000
    volumes:
      - '.:/app'
      - '/app/node_modules'
    depends_on: 
      - backend
    restart: always
    
    