version: "3.7"
services:
  redis:
    image: redis
    volumes:
      - ./data:/data
    ports:
      - 6379:6379
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports: 
      - "6666:6666"
    depends_on: 
      - redis